- block:
    - include_vars:
        file: vars/consul_key.yml
  rescue:
    - include_tasks: keygen.yml
    - include_tasks: config.yml

- name: Updating server config
  template:
    src: '{{ item.src }}.j2'
    dest: '{{ item.dest }}'
  with_items:
    - src: consul/config.json
      dest: /etc/consul.d/config.json
    - src: consul.service
      dest: /etc/systemd/system/consul.service
    - src: consul-dns.service
      dest: /etc/systemd/system/consul-dns.service
  notify: Restart consul

- block:
    - name: Checking local port 53
      wait_for:
        port: 53
        timeout: 3
  rescue:
    - name: Enable DNS port forwarding
      command: '{{ item }}'
      changed_when: false
      with_items:
        - iptables -t nat -A PREROUTING -p udp -m udp --dport 53 -j REDIRECT --to-ports 8600
        - iptables -t nat -A PREROUTING -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 8600
        - iptables -t nat -A OUTPUT -d localhost -p udp -m udp --dport 53 -j REDIRECT --to-ports 8600
        - iptables -t nat -A OUTPUT -d localhost -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 8600
